### ISSUE TITLE
Feature "echo_ratio" error: ValueError('The volume must be a cylinder')

### ISSUE THREAD

**Issue by lbogaardt** [eEcoLiDAR/laserchicken#120]
Feature "echo_ratio" gives an error when calculated over a cell. Should it really only be possible for a cylinder?

`python /home/ubuntu/feature_scripts/computefea_wtargets_cell.py /data/local/eecolidar/modules/python/laserchicken/ /data/local/eecolidar/rclone/tmp/ahn3_256x256_2km_norm/tile_76_79.LAZ /data/local/eecolidar_webdav/01_Work/ALS/Netherlands/ahn3_targets_100m/tile_76_79_target.laz 50 /home/ubuntu/tile_76_79.ply
------ Import is started ------
Number of points: 59068115
Number of points in target: 400
------ Computing neighborhood is started ------
Cylinder size in Bytes: 13697343969.7
Memory size in Bytes: 33737809920
Start tree creation
Done with env tree creation
Done with target tree creation
build kd-tree: 46.099997 sec
Computed neighborhoods list length at iteration 0 is: 400
------ Feature calculation is started ------
Feature "eigenv_3"
Number of targets: 400, number of features: 3
 took 2.69 seconds
Feature "point_density"
Number of targets: 400, number of features: 1
 took 0.70 seconds
Feature "pulse_penetration_ratio"
Number of targets: 400, number of features: 2
 took 23.44 seconds
Feature "echo_ratio"
Number of targets: 400, number of features: 1
Traceback (most recent call last):
  File "/home/ubuntu/feature_scripts/computefea_wtargets_cell.py", line 52, in <module>
    'sigma_z','perc_20','perc_40','perc_60','perc_80','perc_90','echo_ratio','pulse_penetration_ratio','point_density','eigenv_1','eigenv_2','eigenv_3'], Cell(np.float(args.radius)))
  File "/data/local/eecolidar/modules/python/laserchicken/laserchicken/feature_extractor/__init__.py", line 76, in compute_features
    target_point_cloud, extractor, volume, overwrite, kwargs)
  File "/data/local/eecolidar/modules/python/laserchicken/laserchicken/feature_extractor/__init__.py", line 107, in _add_or_update_feature
    target_index+target_idx_base, volume)
  File "/data/local/eecolidar/modules/python/laserchicken/laserchicken/feature_extractor/echo_ratio_feature_extractor.py", line 52, in extract
    raise ValueError('The volume must be a cylinder')
ValueError: The volume must be a cylinder`

**Comment by romulogoncalves** [comment]
Could you share the script you use to extract the feature and point out which src and target point cloud you used?

Does it happen for all files?
